// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

Future<String> initEngine({
  required String cacheDir,
  required InitConfig config,
}) =>
    RustLib.instance.api.crateApiInitEngine(cacheDir: cacheDir, config: config);

Future<String> chatCompletion({required String requestJson}) =>
    RustLib.instance.api.crateApiChatCompletion(requestJson: requestJson);

Stream<String> chatCompletionStream({required String requestJson}) =>
    RustLib.instance.api.crateApiChatCompletionStream(requestJson: requestJson);

enum BackendType { burn, execuTorch, llamaCpp }

class InitConfig {
  final int vocabShards;
  final int maxGenLen;
  final bool useExecutorch;
  final BackendType backend;
  final int speculateTokens;

  const InitConfig({
    required this.vocabShards,
    required this.maxGenLen,
    required this.useExecutorch,
    required this.backend,
    required this.speculateTokens,
  });

  @override
  int get hashCode =>
      vocabShards.hashCode ^
      maxGenLen.hashCode ^
      useExecutorch.hashCode ^
      backend.hashCode ^
      speculateTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InitConfig &&
          runtimeType == other.runtimeType &&
          vocabShards == other.vocabShards &&
          maxGenLen == other.maxGenLen &&
          useExecutorch == other.useExecutorch &&
          backend == other.backend &&
          speculateTokens == other.speculateTokens;
}
