// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDT3YwrtVMFdLIdRAfXmPAclcU0VqcnwY',
    appId: '1:946016760428:web:a44c3c5c89dbb589a71e49',
    messagingSenderId: '946016760428',
    projectId: 'snowglobe-project',
    authDomain: 'snowglobe-project.firebaseapp.com',
    storageBucket: 'snowglobe-project.firebasestorage.app',
    measurementId: 'G-E0Y1QDZW5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp4v8MAhQURim0w3QgN8QXD1gqGrPoIjs',
    appId: '1:946016760428:android:ba36c7d7f3b50497a71e49',
    messagingSenderId: '946016760428',
    projectId: 'snowglobe-project',
    storageBucket: 'snowglobe-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Tb_pUayDV6CG3my0c0J21G-J3WakTUY',
    appId: '1:946016760428:ios:3f80bcff88c49a01a71e49',
    messagingSenderId: '946016760428',
    projectId: 'snowglobe-project',
    storageBucket: 'snowglobe-project.firebasestorage.app',
    iosBundleId: 'com.hejitech.snowglobedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Tb_pUayDV6CG3my0c0J21G-J3WakTUY',
    appId: '1:946016760428:ios:3f80bcff88c49a01a71e49',
    messagingSenderId: '946016760428',
    projectId: 'snowglobe-project',
    storageBucket: 'snowglobe-project.firebasestorage.app',
    iosBundleId: 'com.hejitech.snowglobedemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDT3YwrtVMFdLIdRAfXmPAclcU0VqcnwY',
    appId: '1:946016760428:web:3286515f7575a42ea71e49',
    messagingSenderId: '946016760428',
    projectId: 'snowglobe-project',
    authDomain: 'snowglobe-project.firebaseapp.com',
    storageBucket: 'snowglobe-project.firebasestorage.app',
    measurementId: 'G-TBG6N4JDNF',
  );
}
