// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initEngine({required String cacheDir}) =>
    RustLib.instance.api.crateApiSimpleInitEngine(cacheDir: cacheDir);

Future<String> initSession() =>
    RustLib.instance.api.crateApiSimpleInitSession();

Future<String> generateResponse({
  required String sessionId,
  required String prompt,
}) => RustLib.instance.api.crateApiSimpleGenerateResponse(
  sessionId: sessionId,
  prompt: prompt,
);
