// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FrbSink`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `add`, `from`, `from`

Future<String> initEngine({
  required String cacheDir,
  required InitConfig config,
}) => RustLib.instance.api.crateApiSimpleInitEngine(
  cacheDir: cacheDir,
  config: config,
);

Future<int> getLastAcceptedCount({required String sessionId}) => RustLib
    .instance
    .api
    .crateApiSimpleGetLastAcceptedCount(sessionId: sessionId);

Future<ModelInfo?> getModelInfo() =>
    RustLib.instance.api.crateApiSimpleGetModelInfo();

Future<String> checkBackend() =>
    RustLib.instance.api.crateApiSimpleCheckBackend();

Future<String> initSession() =>
    RustLib.instance.api.crateApiSimpleInitSession();

Stream<String> generateResponse({
  required String sessionId,
  required String prompt,
  required int maxGenLen,
}) => RustLib.instance.api.crateApiSimpleGenerateResponse(
  sessionId: sessionId,
  prompt: prompt,
  maxGenLen: maxGenLen,
);

Future<String> experimentalCompletionWithPte({
  required String ptePath,
  required String prompt,
}) => RustLib.instance.api.crateApiSimpleExperimentalCompletionWithPte(
  ptePath: ptePath,
  prompt: prompt,
);

enum BackendType { burn, execuTorch, llamaCpp }

class InitConfig {
  final int vocabShards;
  final int maxGenLen;
  final bool useExecutorch;
  final BackendType backend;
  final int speculateTokens;

  const InitConfig({
    required this.vocabShards,
    required this.maxGenLen,
    required this.useExecutorch,
    required this.backend,
    required this.speculateTokens,
  });

  @override
  int get hashCode =>
      vocabShards.hashCode ^
      maxGenLen.hashCode ^
      useExecutorch.hashCode ^
      backend.hashCode ^
      speculateTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InitConfig &&
          runtimeType == other.runtimeType &&
          vocabShards == other.vocabShards &&
          maxGenLen == other.maxGenLen &&
          useExecutorch == other.useExecutorch &&
          backend == other.backend &&
          speculateTokens == other.speculateTokens;
}

class ModelInfo {
  final BigInt paramCount;
  final BigInt modelSizeBytes;
  final int numLayers;
  final int hiddenSize;
  final int vocabSize;
  final String runner;
  final String backend;

  const ModelInfo({
    required this.paramCount,
    required this.modelSizeBytes,
    required this.numLayers,
    required this.hiddenSize,
    required this.vocabSize,
    required this.runner,
    required this.backend,
  });

  @override
  int get hashCode =>
      paramCount.hashCode ^
      modelSizeBytes.hashCode ^
      numLayers.hashCode ^
      hiddenSize.hashCode ^
      vocabSize.hashCode ^
      runner.hashCode ^
      backend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelInfo &&
          runtimeType == other.runtimeType &&
          paramCount == other.paramCount &&
          modelSizeBytes == other.modelSizeBytes &&
          numLayers == other.numLayers &&
          hiddenSize == other.hiddenSize &&
          vocabSize == other.vocabSize &&
          runner == other.runner &&
          backend == other.backend;
}
